[mypy]
python_version = 3.14
files = client, exporters, tests
exclude = (?x)(
    ^Notebooks/
    | ^btc-data/
    | ^emulation_logs/
    | ^\.venv/
    | ^\.uv-cache/
  )

check_untyped_defs = True
no_implicit_optional = True
strict_optional = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_configs = True
warn_unused_ignores = True
show_error_codes = True
pretty = True
color_output = True

[mypy-blocksci]
ignore_missing_imports = True
